/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd;

import com.mycompany.plantasvzzombis.FrontEnd.JDialojs.CreacionDeCuenta;

/**
 *
 * @author ricardocastillo
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        creador = new javax.swing.JButton();
        selecionador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        creador.setText("Crear cuenta");
        creador.addActionListener(this::creadorActionPerformed);

        selecionador.setText("Selecionar Cuenta");
        selecionador.addActionListener(this::selecionadorActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selecionador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(creador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecionador)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creadorActionPerformed
        CreacionDeCuenta creador= new CreacionDeCuenta(this, true);
        creador.setVisible(true);
        if(creador.getValidacionDeCreacionDeCuenta()){
            MenuDeJuego menuDeJuego= new MenuDeJuego(creador.getNombreCuenta());
            menuDeJuego.setVisible(true);
            this.dispose();
        }



    }//GEN-LAST:event_creadorActionPerformed

    private void selecionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionadorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selecionador;
    // End of variables declaration//GEN-END:variables
}
