/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd;

import java.awt.Image;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.mycompany.plantasvzzombis.BackEnd.ConstructoresDeJardin.CargadorDeArchivo;

/**
 *
 * @author ricardocastillo
 */
public class MenuDeJuego extends javax.swing.JFrame {
        private String nombreCuenta;
        private String nombreArchivo;
        private String nombreJardin;
        private CargadorDeArchivo cargador = new CargadorDeArchivo();

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(MenuDeJuego.class.getName());

        /**
         * Creates new form MenuDeJuego
         */
        public MenuDeJuego(String nombre) {
                initComponents();
                nombreCuenta = nombre;
                nombreCuentaJLable.setText(nombreCuenta);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Carga tu imagen (asegúrate de tenerla en la carpeta de recursos de tu proyecto)
                Image img = new ImageIcon(getClass().getResource("/com/ricardo/Menus /menuInicio.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        salir = new javax.swing.JButton();
        estadisticas = new javax.swing.JButton();
        partidaGuardada = new javax.swing.JButton();
        nuevaPartida = new javax.swing.JButton();
        nombreCuentaJLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salir.setText("Salir");
        salir.addActionListener(this::salirActionPerformed);

        estadisticas.setText("Estadisticas");
        estadisticas.addActionListener(this::estadisticasActionPerformed);

        partidaGuardada.setText("Partida Guardada");
        partidaGuardada.addActionListener(this::partidaGuardadaActionPerformed);

        nuevaPartida.setText("Nueva Partida");
        nuevaPartida.addActionListener(this::nuevaPartidaActionPerformed);

        nombreCuentaJLable.setText("Nombre Jugador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(partidaGuardada)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombreCuentaJLable)))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreCuentaJLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(nuevaPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partidaGuardada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nuevaPartidaActionPerformed
                JFileChooser selectorDeArchivosFc = new JFileChooser();
                selectorDeArchivosFc.setFileSelectionMode(JFileChooser.FILES_ONLY);

                FileNameExtensionFilter filtro = new FileNameExtensionFilter("JSON De jardin", "JSON");
                selectorDeArchivosFc.setFileFilter(filtro);

                int resultado = selectorDeArchivosFc.showOpenDialog(this);
                if (resultado != JFileChooser.CANCEL_OPTION) {
                        File archivo = selectorDeArchivosFc.getSelectedFile();
                        if (archivo == null || archivo.getName().equals("")) {
                                JOptionPane.showMessageDialog(this, "Error al cargar el acrchivo");
                        } else {
                                nombreArchivo = archivo.getName();
                                nombreJardin = archivo.getName();
                                cargador.cargadorDeJardin(archivo);
                                Jardin jardin = new Jardin(cargador.getCerebrosIniciales(), cargador.getCerebrosIniciales());
                                jardin.setVisible(true);
                        }
                }
        }// GEN-LAST:event_nuevaPartidaActionPerformed

        private void partidaGuardadaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_partidaGuardadaActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_partidaGuardadaActionPerformed

        private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadisticasActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_estadisticasActionPerformed

        private void salirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salirActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_salirActionPerformed

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estadisticas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreCuentaJLable;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JButton partidaGuardada;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
