/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd;

import java.awt.Image;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.mycompany.plantasvzzombis.BackEnd.ConstructoresDeJardin.CargadorDeArchivo;
import com.mycompany.plantasvzzombis.FrontEnd.JDialojs.SelectorDeDificultad;

/**
 *
 * @author ricardocastillo
 */
public class MenuDeJuego extends javax.swing.JFrame {
    private String nombreCuenta;
    private String nombreArchivo;
    private String nombreJardin;
    private CargadorDeArchivo cargador = new CargadorDeArchivo();

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuDeJuego.class.getName());

    /**
     * Creates new form MenuDeJuego
     */
    public MenuDeJuego(String nombre) {
        initComponents();
        nombreCuenta = nombre;
        nombreCuentaJLable.setText(nombreCuenta);

        salir.setOpaque(false);
        salir.setBorderPainted(false);
        salir.setFocusPainted(false);
        partidaGuardada.setOpaque(false);
        partidaGuardada.setBorderPainted(false);
        partidaGuardada.setFocusPainted(false);
        estadisticas.setOpaque(false);
        estadisticas.setBorderPainted(false);
        estadisticas.setFocusPainted(false);
        nuevaPartida.setOpaque(false);
        nuevaPartida.setBorderPainted(false);
        nuevaPartida.setFocusPainted(false);
        revalidate();
        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Carga tu imagen (asegúrate de tenerla en la carpeta de recursos de tu proyecto)
                Image img = new ImageIcon(getClass().getResource("/com/ricardo/Menus /menuInicio.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        salir = new javax.swing.JButton();
        estadisticas = new javax.swing.JButton();
        partidaGuardada = new javax.swing.JButton();
        nuevaPartida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Carga tu imagen (asegúrate de tenerla en la carpeta de recursos de tu proyecto)
                Image img = new ImageIcon(getClass().getResource("/com/ricardo/Menus /FondoMadera.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        nombreCuentaJLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ricardo/Menus /Botones /Boton_Salir.png"))); // NOI18N
        salir.addActionListener(this::salirActionPerformed);

        estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ricardo/Menus /Botones /Boton_Estadisticas.png"))); // NOI18N
        estadisticas.addActionListener(this::estadisticasActionPerformed);

        partidaGuardada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ricardo/Menus /Botones /Boton_PartidaGuardada.png"))); // NOI18N
        partidaGuardada.addActionListener(this::partidaGuardadaActionPerformed);

        nuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ricardo/Menus /Botones /Boton_NuevaPartida.png"))); // NOI18N
        nuevaPartida.addActionListener(this::nuevaPartidaActionPerformed);

        jPanel2.setOpaque(false);
        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        nombreCuentaJLable.setForeground(new java.awt.Color(255, 255, 255));
        nombreCuentaJLable.setText("Nombre Jugador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(nombreCuentaJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreCuentaJLable)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(partidaGuardada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuevaPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(387, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(nuevaPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partidaGuardada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nuevaPartidaActionPerformed
        JFileChooser selectorDeArchivosFc = new JFileChooser();
        selectorDeArchivosFc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JSON De jardin", "JSON");
        selectorDeArchivosFc.setFileFilter(filtro);

        int resultado = selectorDeArchivosFc.showOpenDialog(this);
        if (resultado != JFileChooser.CANCEL_OPTION) {
            File archivo = selectorDeArchivosFc.getSelectedFile();
            if (archivo == null || archivo.getName().equals("")) {
                JOptionPane.showMessageDialog(this, "Error al cargar el acrchivo");
            } else {
                nombreArchivo = archivo.getName();
                nombreJardin = archivo.getName();
                cargador.cargadorDeJardin(archivo);
                SelectorDeDificultad dificultad= new SelectorDeDificultad(this, rootPaneCheckingEnabled);
                dificultad.setVisible(true);
                Jardin jardin = new Jardin(cargador.getCerebrosIniciales(), cargador.getCerebrosIniciales(),
                        cargador.getJardin());
                jardin.setVisible(true);
                this.setVisible(false);
            }
        }
    }// GEN-LAST:event_nuevaPartidaActionPerformed

    private void partidaGuardadaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_partidaGuardadaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_partidaGuardadaActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_estadisticasActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estadisticas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreCuentaJLable;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JButton partidaGuardada;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
