/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ricardocastillo
 */
public class MenuDeJuego extends javax.swing.JFrame {
    private String nombreCuenta;
    private String nombreArchivo;
    private String nombreJardin;

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuDeJuego.class.getName());

    /**
     * Creates new form MenuDeJuego
     */
    public MenuDeJuego(String nombre) {
        initComponents();
        nombreCuenta = nombre;
        nombreCuentaJLable.setText(nombreCuenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCuentaJLable = new javax.swing.JLabel();
        nuevaPartida = new javax.swing.JButton();
        partidaGuardada = new javax.swing.JButton();
        estadisticas = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreCuentaJLable.setText("Nombre Jugador");

        nuevaPartida.setText("Nueva Partida");
        nuevaPartida.addActionListener(this::nuevaPartidaActionPerformed);

        partidaGuardada.setText("Partida Guardada");
        partidaGuardada.addActionListener(this::partidaGuardadaActionPerformed);

        estadisticas.setText("Estadisticas");
        estadisticas.addActionListener(this::estadisticasActionPerformed);

        salir.setText("Salir");
        salir.addActionListener(this::salirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(partidaGuardada,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(nuevaPartida,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(estadisticas,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nombreCuentaJLable)))
                                .addContainerGap(328, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(nombreCuentaJLable)
                                .addGap(60, 60, 60)
                                .addComponent(nuevaPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(partidaGuardada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadisticas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salir)
                                .addContainerGap(124, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nuevaPartidaActionPerformed
        JFileChooser selectorDeArchivosFc = new JFileChooser();
        selectorDeArchivosFc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JSON De jardin", "JSON");
        selectorDeArchivosFc.setFileFilter(filtro);

        int resultado = selectorDeArchivosFc.showOpenDialog(this);
        if (resultado != JFileChooser.CANCEL_OPTION) {
            File archivo = selectorDeArchivosFc.getSelectedFile();
            if (archivo == null || archivo.getName().equals("")) {
                JOptionPane.showMessageDialog(this, "Error al cargar el acrchivo");
            } else {
                nombreArchivo = archivo.getName();
                nombreJardin = archivo.getName();
                
            }
        }
    }// GEN-LAST:event_nuevaPartidaActionPerformed

    private void partidaGuardadaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_partidaGuardadaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_partidaGuardadaActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_estadisticasActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estadisticas;
    private javax.swing.JLabel nombreCuentaJLable;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JButton partidaGuardada;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
