/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd;

import java.awt.Image;

import javax.swing.ImageIcon;

import com.mycompany.plantasvzzombis.FrontEnd.JDialojs.CreacionDeCuenta;

/**
 *
 * @author ricardocastillo
 */
public class MenuPrincipal extends javax.swing.JFrame  {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuPrincipal.class.getName());
    private final static String RUTA_DE_CREADOR = "/com/ricardo/Menus /Botones /Boton_CrearCuentaPrincipal.png";
    private final static String RUTA_DE_SELECION = "/com/ricardo/Menus /Botones /Boton_SelecionarCuenta.png";

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        creadorDeCuenta.setOpaque(false);
        selecionadorCuenta.setOpaque(false);
        creadorDeCuenta.setBorderPainted(false);
        selecionadorCuenta.setBorderPainted(false);
        creadorDeCuenta.setFocusPainted(false);
        selecionadorCuenta.setFocusPainted(false);
        revalidate();
        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Carga tu imagen (asegúrate de tenerla en la carpeta de recursos de tu proyecto)
                Image img = new ImageIcon(getClass().getResource("/com/ricardo/Menus /menuInicio.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        selecionadorCuenta = new javax.swing.JButton();
        creadorDeCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selecionadorCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ricardo/Menus /Botones /Boton_SelecionarCuenta.png"))); // NOI18N

        creadorDeCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ricardo/Menus /Botones /Boton_CrearCuentaPrincipal.png"))); // NOI18N
        creadorDeCuenta.addActionListener(this::creadorDeCuentaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creadorDeCuenta)
                    .addComponent(selecionadorCuenta))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(creadorDeCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecionadorCuenta)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creadorDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creadorDeCuentaActionPerformed
  CreacionDeCuenta creador = new CreacionDeCuenta(this, true);
        creador.setVisible(true);
        if (creador.getValidacionDeCreacionDeCuenta()) {
            MenuDeJuego menuDeJuego = new MenuDeJuego(creador.getNombreCuenta());
            menuDeJuego.setVisible(true);
            this.dispose();
        }    }//GEN-LAST:event_creadorDeCuentaActionPerformed

    private void selecionadorCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selecionadorCuentaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_selecionadorCuentaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creadorDeCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selecionadorCuenta;
    // End of variables declaration//GEN-END:variables
}
