/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd.JDialojs;

import javax.swing.JOptionPane;

import com.mycompany.plantasvzzombis.BackEnd.MetodosStatic;

/**
 *
 * @author ricardocastillo
 */
public class CreacionDeCuenta extends javax.swing.JDialog {
    private boolean valido = false;
    private String nombreUsuario;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(CreacionDeCuenta.class.getName());

    /**
     * Creates new form CreacionDeCuenta
     */
    public CreacionDeCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreDeCuenta = new javax.swing.JTextField();
        crearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Instruciones ");

        nombreDeCuenta.setText("Nombre Cuenta");

        crearCuenta.setText("Crear cuenta");
        crearCuenta.addActionListener(this::crearCuentaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crearCuenta)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearCuenta)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearCuentaActionPerformed
         nombreUsuario = nombreDeCuenta.getText();
        nombreUsuario = nombreUsuario.trim();

        if (nombreUsuario.length() < 12 && nombreUsuario.length() > 0) {
            valido = MetodosStatic.esNombreValido(nombreUsuario);
        }
        if (!valido) {
            JOptionPane.showMessageDialog(null, "Nombre no valido", "Error en el nombre", JOptionPane.ERROR_MESSAGE);
        } else {
            this.dispose();
        }
    }// GEN-LAST:event_crearCuentaActionPerformed

    public boolean getValidacionDeCreacionDeCuenta() {
        return valido;
    }public String getNombreCuenta() {
        return nombreUsuario;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreDeCuenta;
    // End of variables declaration//GEN-END:variables
}
