/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd.JDialojs;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

import java.awt.*;

/**
 *
 * @author ricardocastillo
 */
public class MenuDePausa extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuDePausa.class.getName());

    /**
     * Creates new form MenuDepausa
     */
    public MenuDePausa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);

        setBackground(new Color(0, 0, 0, 0));

        initComponents();
        ((JPanel) getContentPane()).setOpaque(false);
        getContentPane().setBackground(new Color(0, 0, 0, 0));

        fondo.setSize(598, 608);
        fondo.setOpaque(false);
        fondo.setBackground(new Color(0, 0, 0, 0));
        fondo.setDoubleBuffered(true);

        setOpacity(1.0f);

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Carga tu imagen (asegúrate de tenerla en la carpeta de recursos de tu
                // proyecto)
                Image img = new ImageIcon(getClass().getResource("/com/ricardo/Menus /pause_menu.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        salirYGuardar = new javax.swing.JLabel();
        continuar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setUndecorated(true);

        fondo.setBackground(new java.awt.Color(0, 204, 0));

        salirYGuardar.setText("Salir Y guardar");
        salirYGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirYGuardarMouseClicked(evt);
            }
        });

        continuar.setBackground(new java.awt.Color(255, 255, 255));
        continuar.setText("Continuar");
        continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
                fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(salirYGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100,
                                        Short.MAX_VALUE)
                                .addComponent(continuar)
                                .addGap(93, 93, 93)));
        fondoLayout.setVerticalGroup(
                fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fondoLayout.createSequentialGroup()
                                .addContainerGap(253, Short.MAX_VALUE)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(salirYGuardar)
                                        .addComponent(continuar))
                                .addGap(30, 30, 30)));

        getContentPane().add(fondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_continuarMouseClicked
        this.dispose();
    }// GEN-LAST:event_continuarMouseClicked

    private void salirYGuardarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_salirYGuardarMouseClicked
        this.dispose();
    }// GEN-LAST:event_salirYGuardarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel continuar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel salirYGuardar;
    // End of variables declaration//GEN-END:variables
}
