/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.plantasvzzombis.FrontEnd.JDialojs;

import javax.swing.ButtonGroup;

/**
 *
 * @author ricardocastillo
 */
public class SelectorDeDificultad extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(SelectorDeDificultad.class.getName());

    /**
     * Creates new form SelectorDeDificultad
     */
    private void medioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_medioActionPerformed

    }// GEN-LAST:event_medioActionPerformed

    private void facilActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_facilActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_facilActionPerformed

    private void dificilActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dificilActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dificilActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }// GEN-LAST:event_jButton1ActionPerformed

    public SelectorDeDificultad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ButtonGroup grupoBotonesDificultad = new ButtonGroup();
        grupoBotonesDificultad.add(facil);
        grupoBotonesDificultad.add(medio);
        grupoBotonesDificultad.add(dificil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facil = new javax.swing.JToggleButton();
        medio = new javax.swing.JToggleButton();
        dificil = new javax.swing.JToggleButton();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        facil.setText("Facil");
        facil.addActionListener(this::facilActionPerformed);

        medio.setText("Medio");
        medio.addActionListener(this::medioActionPerformed);

        dificil.setText("Dificil");
        dificil.addActionListener(this::dificilActionPerformed);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(this::aceptarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(facil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(aceptar)
                                        .addComponent(dificil))
                                .addContainerGap(21, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(facil)
                                        .addComponent(medio)
                                        .addComponent(dificil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aceptar)
                                .addContainerGap(33, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JToggleButton dificil;
    private javax.swing.JToggleButton facil;
    private javax.swing.JToggleButton medio;
    // End of variables declaration//GEN-END:variables
}
